package VARIABLES;

public class Variables {

     static int x;
    public static void main(String[] args) {
       
        System.out.println(x);
    }
}

//HERE IS THE CODE FOR STATIC VARIABLE 
//WE CAN ACCESS STATIC VARIABLES DIRECTLY FROM BOTH INSTANCE AND STATIC AREA.
//STATIC VARIABLE SHOULD BE DECLEARED WITH IN THE CLASS DIRECTLY.
//NOT IN BLOCK OR METHOD OR CONSTROCTOR
//STATIC VARIABLE ARE CREATED AT THE TIME OF CLASS LOADING 
//JVM WILL PROVIDE DEFAULT VALUE IF WE DOES NOT PROVIED ANY VALUE TO THE VARIABLE