package ACCESSMODIFIERS;
public class PublicModifier {
    public static void m1(){
      System.out.println("public modifier");
    }
    public static void main(String[] args) {
        m1();
    }
}


//THIS IS THE PUBLIC MODIFIER APPILICABLE FOR METHODS AND CLASSESS AND VARIABLES
//EVERY STATIC METHOD IS ALWAYS PUBLIC
//BY DECLEARING A METHOD OR CLASS AS PUBLIC WE CAN ACCESS IT FROM WITH IN THE PACKEG AND OUT SIDE THE PACKAGE
//THIS IS ALSO APPLICABLE FOR INTERFACES ALSO
// THIS IS ALSO APPLICABLE FOR CONSTRUCTOR 
